apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dinhcam89/frontend:v0.0.4-dev
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://api.gke-dev.dinhcam.tech"