apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dinhcam89/frontend:v0.0.7-dev
          ports:
            - containerPort: 80
          # command:
          #   - "/bin/sh"
          #   - "-c"
          # args:
          #   - |
          #     sed -i "s|__api_url__|${REACT_APP_API_URL}|g" /usr/share/nginx/html/env.js && nginx -g "daemon off;";

          env:
            - name: REACT_APP_API_URL
              value: "http://api.gke-dev.dinhcam.tech"